---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Homelab Dashboard"
subtitle: "Wyatt Duberstein's"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Welcome!"
  icon: "fa fa-grin"
  content: "This is my central hub for all hosted sites under the wyattduber.com domain and more. <br /> For more information on myself, check out my <a href='https://www.wyattduber.com/' target='_blank'>personal website</a>.<br><br> To check out the source code of some of the below projects, check out my <a href='https://github.com/wyattduber/' target='_blank'>GitHub</a>!"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Source"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Sharing"
    icon: "fas fa-cloud"
    items:
      - name: "FilePizza"
        subtitle: "Share files directly from your browser"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/filepizza.png"
        url: "https://pizza.wyattduber.com"
      - name: "Paste"
        subtitle: "Text and code snippet sharing"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/paste.svg"
        url: "https://paste.wyattduber.com"
  - name: "Personal/Info"
    icon: "fa-solid fa-person"
    items:
      - name: "Personal Site"
        subtitle: "View my personal site"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/coding.png"
        url: "https://www.wyattduber.com"
      - name: "Resume"
        subtitle: "View my professional resume"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/resume.png"
        url: "https://resume.wyattduber.com"
      - name: "Wedding"
        subtitle: "Our wedding information and updates"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/wedding.png"
        url: "https://wedding.wyattduber.com"
  - name: "Repository"
    icon: "fa-solid fa-code-branch"
    items:
      - name: "Memos"
        subtitle: "Quick notes and memos"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/memos.png"
        url: "https://memos.wyattduber.com"
      - name: "GitLab"
        subtitle: "Version control and code collaboration"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/gitlab.png"
        url: "https://git.wyattduber.com"
      - name: "Plane"
        subtitle: "Track issues, epics, and product roadmaps."
        tag: "app"
        target: "_blank"
        logo: "assets/tools/plane.png"
        url: "https://plane.wyattduber.com" 
      - name: "Repo"
        subtitle: "Simple autoindexed repo site"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/repo.png"
        url: "https://repo.wyattduber.com"
  - name: "Server"
    icon: "fa-solid fa-server"
    items:
      - name: "Homepage"
        subtitle: "Homepage with status/app/search functions"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/homepage.png"
        url: "https://home.wyattduber.com"
      - name: "AMP"
        subtitle: "AMP server management"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/amp.png"
        url: "https://server.wyattduber.com"
      - name: "Nginx Proxy Manager"
        subtitle: "Web server configuration and monitoring"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/nginx.png"
        url: "https://nginx.wyattduber.com"
      - name: "Nextcloud"
        subtitle: "Self-hosted file synchronization and sharing"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/nextcloud.png"
        url: "https://cloud.wyattduber.com"
      - name: "Upptime"
        subtitle: "Uptime status panel for hosted sites"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/upptime.svg"
        url: "https://status.wyattduber.com"
      - name: "SearXNG"
        subtitle: "Free privacy-focused search engine"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/searxng.svg"
        url: "https://search.wyattduber.com"
      - name: "Hoppscotch"
        subtitle: "Postman-esque tool for HTTP requests"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/hoppscotch.png"
        url: "https://hoppscotch.wyattduber.com"
  - name: "Websites"
    icon: "fa-solid fa-sitemap"
    items:
      - name: "iTrakz"
        subtitle: "Personal task and project tracker"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/itrakz.png"
        url: "https://itrakz.wyattduber.com"
      - name: "SE 422X"
        subtitle: "Craigslist Clone Project for College"
        tag: "app"
        target: "_blank"
        logo: "assets/tools/se422x.png"
        url: "https://se422x.wyattduber.com"
      - name: "UMary For Wife"
        subtitle: "Dating website for UMary Students"
        tag: "app"
        target: "_blank"
        url: "https://dating.wyattduber.com"
